insert into users (username, pass_word, email) values ('esigmund0', 'intermediate', 'rbubbings0@sourceforge.net');
insert into users (username, pass_word, email) values ('rmeiklam1', 'neural-net', 'ctaft1@europa.eu');
insert into users (username, pass_word, email) values ('bjouanot2', 'parallelism', 'dstodhart2@google.fr');
insert into users (username, pass_word, email) values ('mpartridge3', 'Re-engineered', 'kstrowan3@gmpg.org');
insert into users (username, pass_word, email) values ('dclopton4', 'optimizing', 'leardley4@unblog.fr');
insert into users (username, pass_word, email) values ('bebhardt5', 'Graphical User Interface', 'iburrel5@psu.edu');
insert into users (username, pass_word, email) values ('jdambrogio6', 'knowledge base', 'sburford6@ask.com');
insert into users (username, pass_word, email) values ('lfeltoe7', 'object-oriented', 'kwallege7@godaddy.com');
insert into users (username, pass_word, email) values ('araleston8', 'knowledge base', 'estennet8@prweb.com');
insert into users (username, pass_word, email) values ('tstelle9', 'instruction set', 'eofallon9@cpanel.net');
insert into users (username, pass_word, email) values ('jchrispa', 'Triple-buffered', 'bcollumbella@whitehouse.gov');
insert into users (username, pass_word, email) values ('egonthardb', 'Up-sized', 'cdoghartieb@diigo.com');
insert into users (username, pass_word, email) values ('mselburnc', 'zero tolerance', 'tlarcierc@elegantthemes.com');
insert into users (username, pass_word, email) values ('lendd', 'encoding', 'kbrazeltond@ucsd.edu');
insert into users (username, pass_word, email) values ('jbarnewelle', 'Configurable', 'holwene@ocn.ne.jp');
insert into users (username, pass_word, email) values ('rmoultrief', 'Upgradable', 'afindleyf@guardian.co.uk');
insert into users (username, pass_word, email) values ('bbrunig', 'dynamic', 'jnolang@bloomberg.com');
insert into users (username, pass_word, email) values ('nmuglestonh', 'function', 'bangeauh@usatoday.com');
insert into users (username, pass_word, email) values ('jpoli', 'scalable', 'amcgirli@theguardian.com');
insert into users (username, pass_word, email) values ('lgrimmerj', 'matrix', 'hgiacomassoj@fastcompany.com');
insert into users (username, pass_word, email) values ('AdminCEO', 'giveMetheMoney', 'headoftheplace@Mycompany.com');
